### ISSUE TITLE
HiDpi scaling on Wayland

### ISSUE THREAD

**Issue by apedicdev** [flathub/org.soapui.SoapUI#11]
Application is not usable when using a 4k display in wayland. Same is for the native app but there is possible to add `JAVA_OPTS="$JAVA_OPTS -Dsun.java2d.uiScale=2"` to the `soapui.sh`. Is it possible with the flatpak version too?
![image](https://github.com/flathub/org.soapui.SoapUI/assets/7457290/8d5b38f3-73d6-44e3-b1e2-1e2293cca01f)

**Comment by apedicdev** [comment]
fixed adding `JAVA_OPTS="$JAVA_OPTS -Dsun.java2d.uiScale=2"` to `soapui-launcher.sh`

**Comment by prodrigestivill** [comment]
By using flatpak when you change manually files I understand that they will be overridden on each `flatpak update` or `flatpak repair`.

I implemented to allowing custom JAVA_OPTS, it will be published around 24h after it gets merged.

Once you updated to the latest version you will be able to modify JAVA_OPTS only by running:
```shell
flatpak override --env=JAVA_OPTS="-Dsun.java2d.uiScale=2" org.soapui.SoapUI
```

Or addind the JAVA_OPTS with your contents using flatseal app.
